language: node_js

node_js: "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm run electron_rebuild

services:
  - redis-server

script:
  - npm test

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - npm run coveralls
  - npm run codecov
